version: '2'

services:
    reverseproxy:
        image: dashboard_reverseproxy
        ports:
            - 80:8080
        restart: always

    crypto-dashboard:
        depends_on:
            - reverseproxy
        image: dashboard_blazor:latest
        restart: always

    crypto-server:
        depends_on:
            - reverseproxy
            - arango
        image: dashboard_server:latest
        restart: always
        enviroment:
            - DB_HOST=arango
    
    swagger-ui:
        depends_on:
            - reverseproxy
        image: swaggerapi/swagger-ui:latest
        restart: always
    
    arango:
        image: arangodb/arangodb
        restart: always
        enviroment:
         - ARANGO_ROOT_PASSWORD=""

